### ISSUE TITLE
Route die veränderte Meta-daten entgegennimmt

### ISSUE THREAD

**Issue by BenediktEngel** [mi-classroom/mi-web-technologien-beiboot-ss2021-BenediktEngel#8]
Zum speichern der Meta-Daten wird eine route benötigt. 
ToDos:
- [ ] Modul zum Exif-Daten schreiben raussuchen
- [ ] ADR dazu erstellen
- [ ] Route aufbauen und daten speichern.
